#############################################################################
# create_vitis_project.tcl  (Vitis 2019.2, Zynq-7000, MYD-Y7Z010/20)
#
# Recreates the working Mini-JLT SCPI console Vitis project from source.
# Reads the XSA straight from the Vivado build output — run the Vivado
# script (or `make` in vivado/) first so vivado/project_build/project_1.xsa
# exists.
#
# Usage (run from the jlt_project repo root):
#   source /tools/Xilinx/Vivado/2019.2/settings64.sh   ;# for XSA gen, if needed
#   source /tools/Xilinx/Vitis/2019.2/settings64.sh
#   xsct vitis/scripts/create_vitis_project.tcl
#
# Expected repo layout:
#   jlt_project/
#   ├── vivado/
#   │   ├── scripts/ ...                    <- your existing Vivado script(s)
#   │   └── project_build/project_1.xsa     <- generated, gitignored
#   └── vitis/
#       ├── scripts/create_vitis_project.tcl   <- this file
#       ├── src/hello_test/helloworld.c
#       └── workspace/                          <- generated, gitignored
#############################################################################

set xsa_path      "./vivado/project_build/project_1.xsa"
set ws_dir        "./vitis/workspace"
set platform_name "ps1"
set domain_name   "standalone_domain"
set proc_name     "ps7_cortexa9_0"
set os_name       "standalone"
set stdout_uart   "ps7_uart_1"

set sysproj_name  "hello_test_system"
set app_name      "hello_test"
set app_src_dir   "./vitis/src/hello_test"

# ---------------------------------------------------------------------------
# Fail loudly and early if the Vivado build hasn't produced an XSA yet,
# instead of letting `platform create` throw an opaque XSCT error.
# ---------------------------------------------------------------------------
if {![file exists $xsa_path]} {
    puts "ERROR: XSA not found at $xsa_path"
    puts "Run the Vivado build first (e.g. \`make\` in vivado/) to generate it."
    exit 1
}

# ---------------------------------------------------------------------------
# Workspace + platform
#   No -no-boot-bsp: the original project keeps the auto-generated FSBL
#   domain (zynq_fsbl, with xilffs/xilrsa), matching the default GUI flow.
# ---------------------------------------------------------------------------
setws $ws_dir

platform create -name $platform_name -hw $xsa_path

# ---------------------------------------------------------------------------
# Application domain (this is where stdin/stdout gets set)
# ---------------------------------------------------------------------------
domain create -name $domain_name -os $os_name -proc $proc_name

domain active $domain_name
bsp config stdin  $stdout_uart
bsp config stdout $stdout_uart

platform generate

# ---------------------------------------------------------------------------
# Application project — Empty Application, sources added manually
# (matches the original: no extra BSP libs, default linker script)
# ---------------------------------------------------------------------------
app create -name $app_name \
    -platform $platform_name \
    -domain $domain_name \
    -sysproj $sysproj_name \
    -template {Empty Application} \
    -lang c

importsources -name $app_name -path $app_src_dir

app build -name $app_name

puts "Workspace rebuilt at: $ws_dir"

#############################################################################
# Notes
# -----
# * If the Vivado design changes (new IP, address map, etc.), re-run the
#   Vivado script to regenerate project_1.xsa, then re-run this script —
#   `platform create` on an existing platform name will refresh it from the
#   new XSA.
# * Only helloworld.c needs to live in vitis/src/hello_test/ — platform.c/.h
#   and platform_config.h from the original project are unused Hello-World-
#   template boilerplate (helloworld.c never includes platform.h), and
#   lscript.ld is auto-generated by Vitis on app creation.
#############################################################################
